version: '3'
services:

  # API
  hubder-api-app:
    container_name: hubder-api-app
    build:
      context: hubder-api
      dockerfile: Dockerfile
    networks:
      - hubder
    ports:
      - 9081:9081
      - 3081:3081
    restart: always
    depends_on:
      - hubder-api-nginx
  hubder-api-nginx:
    container_name: hubder-api-nginx
    build:
      context: hubder-api
      dockerfile: Dockerfile-nginx
    networks:
      - hubder
    ports:
      - 8081:8081
    restart: always

# Hubder network
networks:
  hubder:
    driver: bridge