version: '3'
services:

  # API
  hubder-api-app:
    container_name: hubder-api-app
    build:
      context: hubder-api
      dockerfile: Dockerfile
    networks:
      - hubder
    ports:
      - 9081:9081
      - 3081:3081
    restart: always
    depends_on:
      - hubder-api-nginx
      - hubder-db
  hubder-api-nginx:
    container_name: hubder-api-nginx
    build:
      context: hubder-api
      dockerfile: Dockerfile-nginx
    networks:
      - hubder
    ports:
      - 8081:8081
    restart: always


  # Client
  hubder-client-app:
    container_name: hubder-client-app
    build:
      context: hubder-client
      dockerfile: Dockerfile
    volumes:
      - './hubder-client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    restart: always


  # DB
  hubder-db:
    container_name: hubder-db
    build:
      context: hubder-db
      dockerfile: Dockerfile
    restart: always
    networks:
      - hubder
    ports:
      - 5432:5432

# Hubder network
networks:
  hubder:
    external:
      name: hubder